// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import MapShowController from "./map_show_controller"
application.register("map-show", MapShowController)

import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)

import WardActionController from "./ward_action_controller"
application.register("ward-action", WardActionController)

import WardSubscriptionController from "./ward_subscription_controller"
application.register("ward-subscription", WardSubscriptionController)

import Dropdown from "./dropdown_controller";
application.register("dropdown", Dropdown);

import "chartkick/chart.js"
